Now cleaner in its runtime when sourced, and faster.

diff --git a/http-req-headers b/http-req-headers
--- a/http-req-headers
+++ b/http-req-headers
@@ -21,95 +21,67 @@
 # like cat, wget and lwp-request (GET). It avoids the need to hard code HTTP
 # request headers or remember to periodically revist their values.
 #
-# * Very chromium centric.
+# Currently very chromium centric.
 #
-# * Currently depends on having a display.
+# Currently depends on having a display.
 #
-# * Designed to be sourced or executed. When executed, capture its stdout for
-#   the browser's request headers, one per line. Sourcing repeatedly from the
-#   same runtime context is safe, and will only print the browser headers to
-#   stdout the first time.
+# Designed to be sourced or executed. When executed, capture its stdout for
+# the browser's request headers, one per line. Sourcing repeatedly from the
+# same runtime context is safe, and will only print the browser headers to
+# stdout the first time.
 #
-# * When sourced the browser's headers are available in var HTTP_HEADERS as new
-#   line delimited strings. Access them with new lines active with
-#   'echo -e $HTTP_HEADERS'.
+# When sourced the browser's headers are available in var HTTP_REQ_HEADS
+# as new line delimited strings. Access them with new lines active with
+# 'echo -e $HTTP_REQ_HEADS'.
 #
-# * When sourced, use methods like setCurlHeadersInPseudoRandomOrder, capturing
-#   stdout, for a line of curl cmd-line-formatted HTTP headers in a "random"
-#   order. See method's comments for "randomness" reason. curl often needs (or
-#   at least is most easily) run from eval when using these formatted headers.
+# When sourced, use methods like setCurlHeadersInPseudoRandomOrder, capturing
+# stdout, for a line of curl cmd-line-formatted HTTP headers in a "random"
+# order. See method's comments for "randomness" reason. curl often needs (or
+# at least is most easily) run from eval when using these formatted headers.
 #
-# * When calling methods like setCurlHeadersInPseudoRandomOrder, pass in the
-#   case-sensitive exact names of HTTP request headers (excluding ':' suffix)
-#   to be excluded from its return value, if any. Do this each time the
-#   method's called.
+# When calling methods like setCurlHeadersInPseudoRandomOrder, pass in the
+# case-sensitive exact names of HTTP request headers (excluding ':' suffix)
+# to be excluded from its return value, if any. Do this each time the
+# method's called.
 #
-# * setCurlHeadersInPseudoRandomOrder default behavior is to return a different
-#   (random) User-Agent value each time it's called. To force it instead to
-#   return the same value for User-Agent with each call, use it something like
-#   this:
+# setCurlHeadersInPseudoRandomOrder default behavior is to return a different
+# (random) User-Agent value each time it's called. To force it instead to
+# return the same value for User-Agent with each call, use it something like
+# this:
 #
-#       . http-req-headers &>/dev/null
-#       ua=$( randomUserAgentStringValue )
-#       [loop]
-#           reqHeads=$( setCurlHeadersInPseudoRandomOrder -u "$ua" )
-#           eval curl ... $reqHeads ...
-#       [end loop]
+#     . http-req-headers &>/dev/null
+#     ua=$( randomUserAgentStringValue )
+#     [loop]
+#         reqHeads=$( setCurlHeadersInPseudoRandomOrder -u "$ua" )
+#         eval curl ... $reqHeads ...
+#         ...
+#     [end loop]
 #
-# * The 'GET' and 'Host' HTTP request headers are never included in those
-#   produced by this script.
+# The 'GET' and 'Host' HTTP request headers are never included in those
+# produced by this script.
 #
-# * It only pulls headers from the browser once per day. All other same-day
-#   calls of this script pull headers from file
+# It only pulls headers from the browser once per day. All other same-day
+# calls of this script pull headers from file
 #
-#       $HOME/.[first token of browser var]-http-req-heads
+#     $HOME/.[first token of browser var]-http-req-heads
 #
-# * In addition to when the browser's headers file is older than 24 hours,
-#   each time the script finds it DNE or empty it re-populates it. Thus,
-#   'cat /dev/null' or delete it to force this script to refresh HTTP headers
-#   from the browser.
+# This file's also refreshed when it DNE or is empty.
 
 
-for e in cat chromium cut date grep mktemp ncat ps sed shuf ss tr wc
-do
-    if ! which $e &>/dev/null
-    then
-        echo -e "\n${0##*/} needs ${e}. Didn't find it. Exiting.\n" >&2
-        exit 1
-    fi
-done
-
-
-browser=chromium
-
-# https://developers.whatismybrowser.com/useragents/explore/
-userAgentStrings="$HOME/bin/config/http-user-agent-strings.txt"
-
-if [ ! -f "$userAgentStrings" ] || [ ! -r "$userAgentStrings" ]
-then
-    echo -e "\nCan't read file '$userAgentStrings'. Exiting.\n" >&2
-    exit 1
-fi
-
-
-httpReqHeadsFile="$HOME/.$( echo "$browser"  |
-                            sed -r 's|^ *||' |
-                            cut -d ' ' -f1 )-http-req-heads"
-
-[ ! -f "$httpReqHeadsFile" ] && touch "$httpReqHeadsFile"
-
-if [ ! -r "$httpReqHeadsFile" ] || [ ! -w "$httpReqHeadsFile" ]
-then
-    echo -e "\nCan't access '$httpReqHeadsFile'. Exiting.\n" >&2
-    exit 1
-fi
-
-
-# https://developers.whatismybrowser.com/useragents/explore/
 if [ function != "$( type -t randomUserAgentStringValue )" ]
 then
     function randomUserAgentStringValue
     {
+        # https://developers.whatismybrowser.com/useragents/explore/
+        declare -r \
+               userAgentStrings="$HOME/bin/config/http-user-agent-strings.txt"
+
+        if [ ! -f "$userAgentStrings" ] || [ ! -r "$userAgentStrings" ]
+        then
+            echo -e "\nCan't read file '$userAgentStrings'.\n" >&2
+            return 1
+        fi
+
         local userAgent=$( shuf -n 1 "$userAgentStrings" )
         if [ -z "$userAgent" ]
         then
@@ -123,7 +95,7 @@ fi
 
 
 # Call setCurlHeadersInPseudoRandomOrder as part of setting up each HTTP
-# request that uses the HTTP_HEADERS string produced by this script. Chrome
+# request that uses the HTTP_REQ_HEADS string produced by this script. Chrome
 # sends its basic/standard HTTP request headers in (what what apperas to be) a
 # random order for each request. This function mimics that behavior.
 #
@@ -171,7 +143,7 @@ then
         local headers=""
         local ua=""
         declare IFS=$'\n'
-        for hdr in $( echo -e $HTTP_HEADERS | shuf )
+        for hdr in $( echo -e $HTTP_REQ_HEADS | shuf )
         do
             if echo "$hdr" | grep -vE "^($exculed): " &>/dev/null
             then
@@ -191,29 +163,15 @@ then
 fi
 
 
-# If true, then HTTP_HEADERS has already been populated, so no need
-# to do anything else. This script can be sourced or executed.
-if [ -n "$HTTP_HEADERS" ]
+if [ function != "$( type -t setHttpRequestHeaders )" ]
 then
-    # This script can be sourced or executed. Trying to put the
-    # return and exit in the same expression mostly creates heartache.
-    return &>/dev/null
-    exit
-fi
-
-
-export HTTP_HEADERS=""
-
-
-if [ function != "$( type -t setHttpOutgoingRequestHeaders )" ]
-then
-    function setHttpOutgoingRequestHeaders
+    function setHttpRequestHeaders
     {
         local IFS=$'\n'
         local L
         declare -i I=0
 
-        for L in $( < "$httpReqHeadsFile" )
+        for L in $( < "$HTTP_REQ_HEADS_FILE" )
         do
             if [ -n "$L" ] && echo "$L" | grep -vE "^(GET|Host):? " &>/dev/null
             then
@@ -224,70 +182,102 @@ then
                 # even if it's available in the browser/version we're
                 # imitating, we don't use it:
                 L=$( echo "$L" | sed -r 's/ +sdch,?//g' )
-                HTTP_HEADERS="$HTTP_HEADERS$L\n"
+                HTTP_REQ_HEADS="$HTTP_REQ_HEADS$L\n"
                 echo "$L"
                 I=1+I
             fi
         done
+        export HTTP_REQ_HEADS
     }
-    export setHttpOutgoingRequestHeaders
+    export -f setHttpRequestHeaders
 fi
 
 
-if (( 3 > $( cat "$httpReqHeadsFile" | wc -l ) )) || \
-   [ $( date +%d | sed -r 's|^0+||' ) != $( ls -l "$httpReqHeadsFile" |
-                                                     sed -r 's|   *| |' |
-                                                     cut -d ' ' -f7 ) ]
-then
-    cat /dev/null > "$httpReqHeadsFile"
-else
-    setHttpOutgoingRequestHeaders
+[ -z "$BROWSER" ] && declare -r BROWSER=chromium
 
+[ -z "$HTTP_REQ_HEADS_FILE" ] && \
+    declare -r HTTP_REQ_HEADS_FILE="$HOME/.$( echo "$BROWSER"  |
+                                              sed -r 's|^  *||' |
+                                              cut -d ' ' -f1 )-http-req-heads"
+
+[ ! -f "$HTTP_REQ_HEADS_FILE" ] && touch "$HTTP_REQ_HEADS_FILE"
+
+if [ ! -r "$HTTP_REQ_HEADS_FILE" ] || [ ! -w "$HTTP_REQ_HEADS_FILE" ]
+then
+    echo -e "\nCan't access '$HTTP_REQ_HEADS_FILE'. Exiting.\n" >&2
+    exit 1
+fi
+
+[ -z "$_24_HRS" ] && declare -r _24_HRS=$(( 60 * 60 * 24 ))
+
+if (( _24_HRS < ( $( date +%s ) - $( stat -c %Y "$HTTP_REQ_HEADS_FILE" ) ) )) \
+                        || \
+   (( 3 > $( cat "$HTTP_REQ_HEADS_FILE" | wc -l ) ))
+then
+
+    HTTP_REQ_HEADS=""
+    cat /dev/null > "$HTTP_REQ_HEADS_FILE"
+
+elif [ -z "$HTTP_REQ_HEADS" ]
+then
+    setHttpRequestHeaders
+fi
+
+if [ -n "$HTTP_REQ_HEADS" ]
+then
     # This script can be sourced or executed. Trying to put the
     # return and exit in the same expression mostly creates heartache.
-    if [ -n "$HTTP_HEADERS" ]
-    then
-        return &>/dev/null
-        exit
-    fi
+    return &>/dev/null
+    exit
 fi
 
 
-# Script only gets to this point if httpReqHeadsFile needs (re-)populated.
-echo -e "\nRefreshing HTTP request headers." >&2
-
-declare -i port=1024
+# Script only gets to this point if HTTP_REQ_HEADS_FILE needs refreshed.
 
 
-function startNetcatSever
+for e in chromium grep mktemp ncat ps shuf ss tr
+do
+    if ! which $e &>/dev/null
+    then
+        echo -e "\n${0##*/} needs ${e}. Didn't find it. Exiting.\n" >&2
+        exit 1
+    fi
+done
+
+
+echo -e "\nRefreshing $HTTP_REQ_HEADS_FILE" >&2
+
+
+function captureBrowsersDefaultHttpRequestHeaders
 {
+    declare -i port=1024
+    declare -i ncPid=0
+
     while (( 32000 > port ))
     do
         port=1+port
         cat /etc/services | grep "$port/" &>/dev/null && \
                                             continue # Skip stdrd server ports.
 
-        ncat -lk 127.0.0.1 $port &>"$httpReqHeadsFile" &
+        ncat -lk 127.0.0.1 $port &>"$HTTP_REQ_HEADS_FILE" &
+        ncPid=$!
+        sleep .25             # Give ncat plenty of time to to init and listen.
 
-        ncPid=$!                                    # Intentionally not local.
-        sleep .50                    # Give nc time to start listening on port.
-
-        if ss -ltnp | grep ":$port" | grep "pid=$ncPid" &>/dev/null
+        # Yes, -p. We own ncat and thus -p produces output.
+        if ss -ltnp | grep ":$port" | grep "pid=$ncPid" >&2
         then
             break        # ncat is running on a port that's not already taken^.
 
-        elif [ -n "$ncPid" ]
-        then
-            echo >&2
-            kill -s SIGTERM $ncPid &>/dev/null   # If ncat asks for a taken
-                # port, there's a long delay before it dies^, and it will be
-                # alive long after the ss chain finishes. So kill it here
-                # before next port attempt.
-
-                # ^Unless the port's taken by another ncat instance, then both
-                # run, both listening to the same port, with only one of them
-                # getting incoming data. Ouch!
+        elif [ -n "$ncPid" ]      # If ncat asks for a taken port, there's a
+        then                      # long delay before it dies^, and it will be
+                                  # alive long after ss finishes. So kill it
+                                  # here before next port attempt.
+            echo "ncat failed to listen on ${port}" >&2
+            kill -s SIGTERM $ncPid &>/dev/null
         fi
+        # ^Unless the port's taken by another ncat instance, then both run,
+        # both listening to the same port, with only one of them getting
+        # incoming data.
     done
 
     if ! ps -hp $ncPid -o args &>/dev/null
@@ -295,58 +285,38 @@ function startNetcatSever
         echo -e "\nFailed to start ncat server instance. Exiting." >&2
         exit 1
     fi
-}
 
-
-function stopNetcatServer
-{
-    echo >&2
-    kill -s SIGTERM $ncPid &>/dev/null
-}
-
-
-function captureBrowsersDefaultHttpRequestHeaders
-{
-    # Making a temp Chromium user data dir avoids prevents it openeing an tab
-    # inside of an already running Chromium instance. Having its own data dir
-    # causes an independent instance of it to be started, one that can be
-    # closed independently of other already running instances.
-    tmpDir=$( mktemp -d )
+    # Making a temp Chromium user data dir prevents it from openeing a tab
+    # inside of an already running Chromium instance, allowing it to be
+    # cleanly closed independently of other already running instances.
+    local tmpDir=$( mktemp -d )
 
     # TODO: When a Chormium with a headless mode become the norm, use it.
-    $browser --incognito --no-proxy-server --user-data-dir="$tmpDir" \
+    $BROWSER --incognito --no-proxy-server --user-data-dir="$tmpDir" \
                     http://127.0.0.1:$port/SomeImage.jpg?foo=bar &>/dev/null &
-    local browser_pid=$!
+    local browserPid=$!
 
     declare -i i=0
-    while (( 30 > i )) && [ ! -s "$httpReqHeadsFile" ]
+    while (( 200 > i )) && [ ! -s "$HTTP_REQ_HEADS_FILE" ]
     do
         i=i+1
         sleep .1
     done
-    sleep .2         # Some time to (hopefully) ensure all headers are written.
+    sleep .2                                  # Ensure all headers are written.
 
-    if [ ! -s "$httpReqHeadsFile" ]
+    if [ ! -s "$HTTP_REQ_HEADS_FILE" ]
     then
-        echo "\nERROR: Didn't capture $browser's HTTP request headers!\n" >&2
+        echo -e "\nERROR: Didn't capture $BROWSER's HTTP req headers!\n" >&2
     fi
 
-    setHttpOutgoingRequestHeaders
+    kill -s SIGINT $browserPid &>/dev/null
 
-    # If the browser above opened in an existing window, its initial process
-    # will have exited by now, and thus its pid will no longer exist. Trying to
-    # kill it will do no harm because the OS does not reuse a process ID too
-    # soon. If its pid still exists at this point, then it started its own
-    # window, and closing that window is the purpose of this kill call. SIGINT
-    # is enough to stop it, and using SIGQUIT causes a message about its
-    # exit to be pushed to the console, which does not happen with SIGINT.
-    kill -s SIGINT $browser_pid &>/dev/null
+    [ -d "$tmpDir" ] && rm -rf "$tmpDir" &>/dev/null
+
+    kill -s SIGTERM $ncPid &>/dev/null
 }
 
-
-startNetcatSever
 captureBrowsersDefaultHttpRequestHeaders
-stopNetcatServer
-
-[ -d "$tmpDir" ] && rm -rf "$tmpDir" &>/dev/null
+unset -f captureBrowsersDefaultHttpRequestHeaders
+setHttpRequestHeaders
 
