React well to iptbls-hole call failures.

diff --git a/iptbls-ssh-shell b/iptbls-ssh-shell
--- a/iptbls-ssh-shell
+++ b/iptbls-ssh-shell
@@ -32,6 +32,12 @@ then
     exit 1
 fi
 
+function cleanUp
+{
+    rm -f "$TF"
+    iptbls-hole -a c -d o -p t -n 22
+}
+
 userHome=$( cat /etc/passwd | grep -E "^$SUDO_USER:" | cut -d : -f6 )
 TF=$( sudo -u $SUDO_USER mktemp )
 echo ". $userHome/.bashrc"                              > "$TF"
@@ -41,13 +47,18 @@ echo "cd $PWD"                                         >> "$TF"
 echo "env | grep SSH"                                  >> "$TF"
 
 
-iptbls-hole -a o -d o -p t -n 22
+if ! iptbls-hole -a o -d o -p t -n 22
+then
+    echo -e "\niptbls-hole open hole call failed.\a"
+    cleanUp
+    exit 1
+fi
+
 trap "iptbls-hole -a c -d o -p t -n 22" \
                           SIGHUP SIGINT SIGQUIT SIGILL SIGABRT SIGFPE SIGTERM
                          #  1      2       3      4       6      8      15
 
 sudo --login -u $SUDO_USER ssh-agent bash --rcfile "$TF"
 
-rm -f "$TF"
-iptbls-hole -a c -d o -p t -n 22
+cleanUp
 
